spring.application.name=basicbooksapi

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/basicbooksdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:apiuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:verystrongpassword}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true

logging.level.fr.fergalmechin.basicbooksapi=DEBUG
