spring.application.name=basicbooksapi

spring.datasource.url=jdbc:postgresql://localhost:5432/basicbooksdb
spring.datasource.username=apiuser
spring.datasource.password=verystrongpassword
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
